---
title: danny.is
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: hi@danny.is
description:
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl:
url:
twitter_username: dannysmith
github_username: dannysmith
theme: minima
plugins:
  - jekyll-feed
  - jekyll-optional-front-matter
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: default
      author: Danny
