---
title: danny.is
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
  - scope:
      path: ''
    values:
      layout: default
  - scope:
      path: _pages
    values:
      layout: default
      permalink: '/:basename/'
  - scope:
      path: _posts
      type: posts
    values:
      layout: essay
      permalink: '/writing/:slug'
  - scope:
      path: _drafts
      type: posts
    values:
      layout: essay
email: hi@danny.is
description: Danny Smith is a person. I need to complete this.
plugins:
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-seo-tag
  - jekyll-redirect-from
include:
  - _pages
